// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnUmd9ppYRgWMU6NOF91nRcxi4gNIj070',
    appId: '1:80736264506:web:1c31407f1b4134e6943003',
    messagingSenderId: '80736264506',
    projectId: 'vox-finance',
    authDomain: 'vox-finance.firebaseapp.com',
    storageBucket: 'vox-finance.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDZZNnxxwb3ltHVItlVqBOp4vUA3yU9RQ',
    appId: '1:80736264506:android:ba5deccbf182dbe0943003',
    messagingSenderId: '80736264506',
    projectId: 'vox-finance',
    storageBucket: 'vox-finance.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCagQYCP-m1hkvVnyQwuykAwb9MxhDlYwc',
    appId: '1:80736264506:ios:0bc23210516f2f0f943003',
    messagingSenderId: '80736264506',
    projectId: 'vox-finance',
    storageBucket: 'vox-finance.firebasestorage.app',
    iosBundleId: 'com.example.voxFinance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCagQYCP-m1hkvVnyQwuykAwb9MxhDlYwc',
    appId: '1:80736264506:ios:0bc23210516f2f0f943003',
    messagingSenderId: '80736264506',
    projectId: 'vox-finance',
    storageBucket: 'vox-finance.firebasestorage.app',
    iosBundleId: 'com.example.voxFinance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnUmd9ppYRgWMU6NOF91nRcxi4gNIj070',
    appId: '1:80736264506:web:48aa964ee78d53d1943003',
    messagingSenderId: '80736264506',
    projectId: 'vox-finance',
    authDomain: 'vox-finance.firebaseapp.com',
    storageBucket: 'vox-finance.firebasestorage.app',
  );
}
